version: 2
jobs:
  deploy_functions:
    docker:
    - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: npm install
    - run: sudo npm install -g firebase-tools

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}


    - run: cd functions && npm install
    - run: cd functions && npm run deploy

workflows:
  version: 2
  tagged_deploy:
    jobs:
    - deploy_functions:
        filters:
          tags:
            only: /^v\d+\.\d+\.\d+$/
          branches:
            ignore: /.*/